Removing two invalid DNS entries from malware.txt
blocklistproject/Lists pull request #1204
Opened 2024-03-29 12:46 UTC by aww-yiss

Signed-off-by: Josh Bradley <jbradley@deimos.lan>

## Summary

## Checklist

- [ ] I have verified that I have not modified the following files:
      - inside the `adguard` folder
      - inside the `alt-version` folder
      - inside the `dnsmasq-version` folder
      - everything.txt

Because those files will be automatically updated using GitHub Actions!

2024-03-30 03:38 UTC, spirillen requested changes
You need to remove two more records...

2024-03-30 03:38 UTC, spirillen commented on malware.txt
>  0.0.0.0 usaa.com.inet.entlogon.logon.redirectjsp.ef4bce064403e276e26b792bda81c384ce09593b819e632a1.3923ef2c8955cooskieid112824nosdeasd.
This line is invalid as well...

2024-03-30 03:38 UTC, spirillen commented on malware.txt
>  0.0.0.0 protection201-account.6827-update.team.com8serv1130.webs001231cr-cm-lgin-submmit-id99-l0gin-submito9-id.ppi11781-lo0gin-loogiin
This line is invalid as well...

2024-03-31 23:01 UTC, aww-yiss commented on malware.txt
>  0.0.0.0 usaa.com.inet.entlogon.logon.redirectjsp.ef4bce064403e276e26b792bda81c384ce09593b819e632a1.3923ef2c8955cooskieid112824nosdeasd.
fixed thanks

2024-03-31 23:01 UTC, aww-yiss commented on malware.txt
>  0.0.0.0 protection201-account.6827-update.team.com8serv1130.webs001231cr-cm-lgin-submmit-id99-l0gin-submito9-id.ppi11781-lo0gin-loogiin
fixed thanks

2024-03-31 23:03 UTC, aww-yiss commented
@spirillen  per your observation, there were several malformed entries in here. I've scrub all the values to check that they at. least end in a valid DNS TLD which has at a minimum some SOA when querying google's 8.8.8.8 resolver.

2024-04-02 12:39 UTC, spirillen commented
@aww-yiss for another time, just use [pyfunceble](https://github.com/funilrys/pyfunceble) :smirk: , then you safe your self a lot of work and google spying

it is as simple as 

```bash
pyfunceble --syntax -f $file
```

2024-08-19 03:15 UTC, merged